/// معلومات الدولة
class CountryData {
  final String name; // English name
  final String nameAr; // Arabic name
  final String code; // Country code
  final String region; // Region code
  final List<String> prefixes; // Valid prefixes
  final int minLength; // Minimum number length
  final int maxLength; // Maximum number length

  const CountryData({
    required this.name,
    required this.nameAr,
    required this.code,
    required this.region,
    required this.prefixes,
    this.minLength = 9,
    this.maxLength = 12,
  });

  /// قائمة الدول كاملة
  static final List<CountryData> countries = [
    // ============= الدول العربية =============
    CountryData(
      name: 'Yemen',
      nameAr: 'اليمن',
      code: '967',
      region: 'YE',
      prefixes: ['71', '73', '77', '70', '78'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Saudi Arabia',
      nameAr: 'السعودية',
      code: '966',
      region: 'SA',
      prefixes: ['5', '05'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Jordan',
      nameAr: 'الأردن',
      code: '962',
      region: 'JO',
      prefixes: ['77', '78', '79', '7'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Egypt',
      nameAr: 'مصر',
      code: '20',
      region: 'EG',
      prefixes: [
        '10',
        '11',
        '12',
        '15',
        '100',
        '101',
        '102',
        '103',
        '104',
        '105',
        '106',
        '107',
        '108',
        '109',
      ],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Iraq',
      nameAr: 'العراق',
      code: '964',
      region: 'IQ',
      prefixes: ['77', '78', '79', '75', '76', '71', '73'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Sudan',
      nameAr: 'السودان',
      code: '249',
      region: 'SD',
      prefixes: ['91', '92', '93', '94', '95', '96', '99', '10', '11', '12'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'UAE',
      nameAr: 'الإمارات',
      code: '971',
      region: 'AE',
      prefixes: ['50', '52', '55', '56', '58'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Kuwait',
      nameAr: 'الكويت',
      code: '965',
      region: 'KW',
      prefixes: ['5', '6', '9', '4'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Qatar',
      nameAr: 'قطر',
      code: '974',
      region: 'QA',
      prefixes: ['33', '55', '66', '77'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Bahrain',
      nameAr: 'البحرين',
      code: '973',
      region: 'BH',
      prefixes: ['36', '66', '77'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Oman',
      nameAr: 'عمان',
      code: '968',
      region: 'OM',
      prefixes: ['71', '72', '73', '78', '79', '90', '91', '92'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Lebanon',
      nameAr: 'لبنان',
      code: '961',
      region: 'LB',
      prefixes: ['70', '71', '76', '78', '79', '81', '3'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Palestine',
      nameAr: 'فلسطين',
      code: '970',
      region: 'PS',
      prefixes: ['56', '58', '59'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Libya',
      nameAr: 'ليبيا',
      code: '218',
      region: 'LY',
      prefixes: ['91', '92', '94', '95'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Tunisia',
      nameAr: 'تونس',
      code: '216',
      region: 'TN',
      prefixes: [
        '21',
        '22',
        '23',
        '51',
        '52',
        '53',
        '54',
        '55',
        '56',
        '91',
        '92',
        '93',
        '94',
        '95',
      ],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Algeria',
      nameAr: 'الجزائر',
      code: '213',
      region: 'DZ',
      prefixes: ['5', '6', '7'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Morocco',
      nameAr: 'المغرب',
      code: '212',
      region: 'MA',
      prefixes: [
        '61',
        '62',
        '63',
        '64',
        '65',
        '66',
        '67',
        '68',
        '69',
        '70',
        '71',
      ],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Mauritania',
      nameAr: 'موريتانيا',
      code: '222',
      region: 'MR',
      prefixes: ['2', '3', '4', '5'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Somalia',
      nameAr: 'الصومال',
      code: '252',
      region: 'SO',
      prefixes: [
        '61',
        '62',
        '63',
        '64',
        '65',
        '66',
        '67',
        '68',
        '69',
        '70',
        '71',
        '72',
        '73',
        '90',
        '91',
      ],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Djibouti',
      nameAr: 'جيبوتي',
      code: '253',
      region: 'DJ',
      prefixes: ['77'],
      minLength: 8,
      maxLength: 8,
    ),
    CountryData(
      name: 'Comoros',
      nameAr: 'جزر القمر',
      code: '269',
      region: 'KM',
      prefixes: ['32', '33', '34', '35', '36', '37', '38', '39', '76', '77'],
      minLength: 7,
      maxLength: 7,
    ),

    // ============= الدول العالمية =============
    CountryData(
      name: 'United States',
      nameAr: 'الولايات المتحدة',
      code: '1',
      region: 'US',
      prefixes: ['2', '3', '4', '5', '6', '7', '8', '9'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'United Kingdom',
      nameAr: 'المملكة المتحدة',
      code: '44',
      region: 'GB',
      prefixes: ['7'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Germany',
      nameAr: 'ألمانيا',
      code: '49',
      region: 'DE',
      prefixes: ['15', '16', '17'],
      minLength: 10,
      maxLength: 11,
    ),
    CountryData(
      name: 'France',
      nameAr: 'فرنسا',
      code: '33',
      region: 'FR',
      prefixes: ['6', '7'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Italy',
      nameAr: 'إيطاليا',
      code: '39',
      region: 'IT',
      prefixes: ['3'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Spain',
      nameAr: 'إسبانيا',
      code: '34',
      region: 'ES',
      prefixes: ['6', '7'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Turkey',
      nameAr: 'تركيا',
      code: '90',
      region: 'TR',
      prefixes: ['5', '53', '54', '55'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Russia',
      nameAr: 'روسيا',
      code: '7',
      region: 'RU',
      prefixes: ['9'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'China',
      nameAr: 'الصين',
      code: '86',
      region: 'CN',
      prefixes: ['1'],
      minLength: 11,
      maxLength: 11,
    ),
    CountryData(
      name: 'India',
      nameAr: 'الهند',
      code: '91',
      region: 'IN',
      prefixes: ['6', '7', '8', '9'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Pakistan',
      nameAr: 'باكستان',
      code: '92',
      region: 'PK',
      prefixes: ['3'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Bangladesh',
      nameAr: 'بنغلاديش',
      code: '880',
      region: 'BD',
      prefixes: ['1', '7', '8', '9'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Indonesia',
      nameAr: 'إندونيسيا',
      code: '62',
      region: 'ID',
      prefixes: ['8'],
      minLength: 10,
      maxLength: 12,
    ),
    CountryData(
      name: 'Malaysia',
      nameAr: 'ماليزيا',
      code: '60',
      region: 'MY',
      prefixes: ['1'],
      minLength: 9,
      maxLength: 10,
    ),
    CountryData(
      name: 'Australia',
      nameAr: 'أستراليا',
      code: '61',
      region: 'AU',
      prefixes: ['4'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Canada',
      nameAr: 'كندا',
      code: '1',
      region: 'CA',
      prefixes: ['2', '3', '4', '5', '6', '7', '8', '9'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Brazil',
      nameAr: 'البرازيل',
      code: '55',
      region: 'BR',
      prefixes: ['11', '12', '13', '14', '15', '16', '17', '18', '19'],
      minLength: 11,
      maxLength: 11,
    ),
    CountryData(
      name: 'South Africa',
      nameAr: 'جنوب أفريقيا',
      code: '27',
      region: 'ZA',
      prefixes: ['6', '7', '8'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Nigeria',
      nameAr: 'نيجيريا',
      code: '234',
      region: 'NG',
      prefixes: ['70', '80', '81', '90', '91'],
      minLength: 10,
      maxLength: 10,
    ),

    // ============= دول جديدة مهمة =============
    CountryData(
      name: 'Afghanistan',
      nameAr: 'أفغانستان',
      code: '93',
      region: 'AF',
      prefixes: ['70', '71', '72', '73', '74', '75', '76', '77', '78', '79'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Iran',
      nameAr: 'إيران',
      code: '98',
      region: 'IR',
      prefixes: ['91', '92', '93', '94', '95', '96', '97', '98', '99', '90'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Nepal',
      nameAr: 'نيبال',
      code: '977',
      region: 'NP',
      prefixes: ['98', '97', '96', '95', '94', '93'],
      minLength: 10,
      maxLength: 10,
    ),
    CountryData(
      name: 'Sri Lanka',
      nameAr: 'سريلانكا',
      code: '94',
      region: 'LK',
      prefixes: ['71', '72', '73', '74', '75', '76', '77', '78'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Myanmar',
      nameAr: 'ميانمار',
      code: '95',
      region: 'MM',
      prefixes: ['97', '99', '95', '96', '98', '94', '93'],
      minLength: 9,
      maxLength: 10,
    ),
    CountryData(
      name: 'Ethiopia',
      nameAr: 'إثيوبيا',
      code: '251',
      region: 'ET',
      prefixes: ['91', '92', '93', '94', '95', '96', '97', '98', '99', '90'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Kenya',
      nameAr: 'كينيا',
      code: '254',
      region: 'KE',
      prefixes: ['71', '72', '73', '74', '75', '76', '77', '78', '79', '70'],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Tanzania',
      nameAr: 'تنزانيا',
      code: '255',
      region: 'TZ',
      prefixes: [
        '61',
        '62',
        '63',
        '64',
        '65',
        '66',
        '67',
        '68',
        '69',
        '71',
        '72',
        '73',
        '74',
        '75',
        '76',
        '77',
        '78',
        '79',
      ],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Uganda',
      nameAr: 'أوغندا',
      code: '256',
      region: 'UG',
      prefixes: [
        '70',
        '71',
        '72',
        '73',
        '74',
        '75',
        '76',
        '77',
        '78',
        '79',
        '31',
        '32',
      ],
      minLength: 9,
      maxLength: 9,
    ),
    CountryData(
      name: 'Ghana',
      nameAr: 'غانا',
      code: '233',
      region: 'GH',
      prefixes: ['20', '24', '27', '50', '54', '55', '57', '59'],
      minLength: 9,
      maxLength: 9,
    ),
  ];

  @override
  String toString() => '$name ($code)';
}
